// Mocks generated by Mockito 5.4.2 from annotations
// in frontend/test/initial_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:frontend/repositories/account_repository.dart' as _i5;
import 'package:frontend/services/firebase_auth_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:openapi/api.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirebaseAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthService extends _i1.Mock
    implements _i2.FirebaseAuthService {
  @override
  _i3.Stream<_i4.User?> get userChanges => (super.noSuchMethod(
        Invocation.getter(#userChanges),
        returnValue: _i3.Stream<_i4.User?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.User?>.empty(),
      ) as _i3.Stream<_i4.User?>);
  @override
  _i3.Future<_i4.User?> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue: _i3.Future<_i4.User?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.User?>.value(),
      ) as _i3.Future<_i4.User?>);
  @override
  _i3.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i5.AccountRepository {
  @override
  _i3.Future<_i6.CreateUserResponse?> createUser(
          _i6.CreateUserRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [request],
        ),
        returnValue: _i3.Future<_i6.CreateUserResponse?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.CreateUserResponse?>.value(),
      ) as _i3.Future<_i6.CreateUserResponse?>);
  @override
  _i3.Future<_i6.LoginResponse?> login() => (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
        ),
        returnValue: _i3.Future<_i6.LoginResponse?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.LoginResponse?>.value(),
      ) as _i3.Future<_i6.LoginResponse?>);
}
