// Mocks generated by Mockito 5.4.2 from annotations
// in frontend/test/main_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i4;
import 'package:frontend/presentation/notifier/splash_page_state_notifier.dart'
    as _i3;
import 'package:frontend/presentation/state/splash_page_state.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSplashPageState_0 extends _i1.SmartFake
    implements _i2.SplashPageState {
  _FakeSplashPageState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SplashPageStateNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSplashPageStateNotifier extends _i1.Mock
    implements _i3.SplashPageStateNotifier {
  MockSplashPageStateNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i4.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);
  @override
  _i5.Stream<_i2.SplashPageState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.SplashPageState>.empty(),
      ) as _i5.Stream<_i2.SplashPageState>);
  @override
  _i2.SplashPageState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSplashPageState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.SplashPageState);
  @override
  set state(_i2.SplashPageState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.SplashPageState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeSplashPageState_0(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.SplashPageState);
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  void consumeEvent(_i2.SplashPageUiEvent? event) => super.noSuchMethod(
        Invocation.method(
          #consumeEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool updateShouldNotify(
    _i2.SplashPageState? old,
    _i2.SplashPageState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i4.RemoveListener addListener(
    _i6.Listener<_i2.SplashPageState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i4.RemoveListener);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
