openapi: 3.0.0
info:
  title: MOL API
  description: アプリ向けAPI仕様
  version: 1.0.0
  contact:
    name: Shoutarou Ohnishi
    email: shoutarou.ohnishi@gmail.com

servers:
  - url: "http://localhost/api/v1"
    description: ローカル環境
  - url: "https://dev.mol.ninja/api/v1"
    description: Dev環境

tags:
  - name: auth
    description: 認証
  - name: user
    description: ユーザー
  - name: room
    description: 対戦ルーム

components:
  securitySchemes:
    firebaseTokenGuard:
      type: http
      bearerFormat: JWT
      scheme: bearer
    appTokenGuard:
      type: http
      bearerFormat: JWT
      scheme: bearer

paths:
  /api/v1/users:
    $ref: './paths/user/user.yaml'
  /api/v1/login:
    $ref: './paths/auth/login.yaml'
  /api/v1/rooms:
    $ref: './paths/room/room.yaml'
  /api/v1/rooms/{room}/members:
    $ref: './paths/room/member.yaml'


