openapi: 3.0.0
info:
  title: MOL API
  description: アプリ向けAPI仕様
  version: 1.0.0
  contact:
    name: Shoutarou Ohnishi
    email: shoutarou.ohnishi@gmail.com

servers:
  - url: "http://localhost/api/v1"
    description: ローカル環境
  - url: "https://dev.mol.ninja/api/v1"
    description: Dev環境

tags:
  - name: auth

components:
  securitySchemes:
    firebaseTokenGuard:
      type: http
      bearerFormat: JWT
      scheme: bearer
    appTokenGuard:
      type: http
      bearerFormat: JWT
      scheme: bearer

paths:
  /api/v1/user:
    $ref: './paths/user/user.yaml'
  /api/v1/login:
    $ref: './paths/auth/login.yaml'


